# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URL": "00_dataset.ipynb",
         "CMUDict": "00_dataset.ipynb",
         "Encoder": "01_seq2seq.ipynb",
         "NewDecoder": "01_seq2seq.ipynb",
         "Seq2Seq": "01_seq2seq.ipynb"}

modules = ["nlp/datasets/cmudict.py",
           "nlp/seq2seq.py"]

doc_url = "https://pmaxit.github.io/mllib/"

git_url = "https://github.com/pmaxit/mllib/tree/master/"

def custom_doc_links(name): return None
