# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URL": "00_core.ipynb",
         "CMUDict": "00_core.ipynb"}

modules = ["nlp/datasets/cmudict.py"]

doc_url = "https://pmaxit.github.io/mllib/"

git_url = "https://github.com/pmaxit/mllib/tree/master/"

def custom_doc_links(name): return None
